
version: "3.3"
services:
  location_track2:
    build:
      context: .
      dockerfile: config_files/Dockerfile
      args:
        buildno: 1
    image:
      location_img
    container_name: location_track2
    env_file:
      - .env
    command:
      sh  /project/config_files/startup.sh
#      gunicorn -b 0.0.0.0:5000 test_flask:app
    # entrypoint:
    #   # serve -s build
    #   /bin/ # For the dev server
    ports:
      - "8082:5000"
      - "8083:5001"
      - "8090:8090"
    volumes:
      - '/app/node_modules'
      - /mnt/fast_storage/appdata/location_tracks:/data
      # - /home/benjamin/docker_installs/location_track/:/data
      - /home/benjamin/docker_installs/location_track/:/project
    networks:
      - traefik_proxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.location_track2.rule=Host(`${WEBAPP_DOMAIN}`)"
      - "traefik.http.routers.location_track2.tls.certresolver=leresolver"
      - "traefik.http.routers.location_track2.entrypoints=websecure"
      # - "traefik.http.services.picasafront.loadbalancer.server.port=5000"
      - "traefik.http.services.location_track2.loadbalancer.server.port=5000"
      - "traefik.http.services.location_track2.loadbalancer.healthcheck.hostname=${WEBAPP_DOMAIN}"
      - "traefik.http.middlewares.location_track2.redirectscheme.scheme=https"
      - "traefik.http.middlewares.location_track2.redirectscheme.permanent=true"
      # Login and password
      # - "traefik.http.routers.location_track.middlewares=auth_track"
      # - "traefik.http.middlewares.auth_track.basicauth.users=recorder:$$apr1$$vnt0xdo8$$juPx9Fw.FXWplz4BKFiz5/"


networks:
  default: 
    driver: bridge
  traefik_proxy:
    external: true
