version: "3.9"
services:

   # Note: On the Cloudflare zero trust dashboard, this app
   # has a hostname of owntracks.exploretheworld.tech, and is
   # running as service http://location_track:5000, since the
   # container name is location_track and the default port is 
   # 5000. It is also on the same docker network, traefik_proxy,
   # as the cloudflared container.
   location_track:
    build:
      context: .
      dockerfile: config_files/Dockerfile
      args:
        buildno: 1
    image:
      location_img
    container_name: location_track
    external_links:
      - cloudflared-tunnel 
    env_file:
      - .env
    command:
      sh  /project/config_files/startup.sh
    volumes:
      - '/app/node_modules'
      - /mnt/fast_storage/appdata/location_tracks:/data
      - /home/benjamin/docker_via_tunnels/location_track/:/project
    networks:
      - traefik_proxy
    restart: always
    environment:
      - TZ=America/New_York

networks:
  default: 
    driver: bridge
  traefik_proxy:
    external: true
