version: "3.9"
services:

   location_track:
    build:
      context: .
      dockerfile: config_files/Dockerfile
      args:
        buildno: 1
    image:
      location_img
    container_name: location_track
    env_file:
      - .env
    command:
      sh  /project/config_files/startup.sh
    volumes:
      - '/app/node_modules'
      - /mnt/fast_storage/appdata/location_tracks:/data
      - /home/benjamin/docker_installs/location_track/:/project
    networks:
      - traefik_proxy
    restart: always
    environment:
      - TZ=America/New_York

networks:
  default: 
    driver: bridge
  traefik_proxy:
    external: true
